[[actions]]
type = "create_table"
name = "bookmarks"
primary_key = ["id"]

            [[actions.columns]]
            name = "id"
            type = "SERIAL"

            [[actions.columns]]
            name = "url"
            type = "text"
            nullable = false
            unique = true

            [[actions.columns]]
            name = "title"
            type = "text"
            nullable = false

            [[actions.columns]]
            name = "body"
            type = "text"

            [[actions.columns]]
            name = "created_at"
            type = "timestamptz"
            default = "now()"

[[actions]]
type = "add_column"
table = "bookmarks"

      [actions.column]
      name = "search"
      type = "tsvector"
      generated = """
      always as (
        setweight(to_tsvector('english', title), 'A') || ' ' ||
        setweight(to_tsvector('english', body), 'B') || ' ' ||
        setweight(to_tsvector('simple', url), 'C') :: tsvector
      ) stored
      """

[[actions]]
type = "add_index"
table = "bookmarks"

      [actions.index]
      name = "idx_search"
      columns = ["search"]
      type = "GIN"
      
